[package]
name = "intan_experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
hound = "3.5.1"
ndarray = "0.15.6"
rodio = "0.17.3"
